### ISSUE TITLE
Image resource for Wiki

### ISSUE THREAD

**Issue by glcj** [apache/plc4x-extras#192]
Toddy Industrial
![toddy](https://github.com/user-attachments/assets/d4111fbb-e6ac-4cee-b521-6f95a858ff27)

Toddy with PLC

![toddyconplc](https://github.com/user-attachments/assets/c46b6c3b-d28f-4d19-a3b1-b0a320aae876)
![s7](https://github.com/user-attachments/assets/5cf04817-b10d-4968-bec9-7f296dfbf7ef)
![s7_warning](https://github.com/user-attachments/assets/1dfa33d9-d822-48a0-b082-f20378662493)
![s7_tip](https://github.com/user-attachments/assets/12a7ce59-609b-42ef-9660-2eb16d14abb9)
![s7_note](https://github.com/user-attachments/assets/a91e92c3-9e7a-4fc9-bd96-82bef68f598b)
![s7_important](https://github.com/user-attachments/assets/aab44482-a3bd-4b19-9353-bf9d33b28f8e)
![s7_ex](https://github.com/user-attachments/assets/898e81e3-c964-41a9-863a-cd2627f462c4)
![s7_dont](https://github.com/user-attachments/assets/7c71256c-58c5-4ddf-bde5-65643e499aee)
![s7_danger](https://github.com/user-attachments/assets/7cf7810d-496f-4938-a1e4-b1d1930f86c9)
![s7_caution](https://github.com/user-attachments/assets/ee08f906-c6eb-451b-b510-8247bf7c15a8)
![s7_banner](https://github.com/user-attachments/assets/30bbb9b8-0aa6-4d8c-84d8-cf905dc4c7ff)
![s7_alert](https://github.com/user-attachments/assets/7cbde823-4bca-4b2f-a1b7-abf31285828a)

Splash screen for Malbec

![Splash_plc4x](https://github.com/user-attachments/assets/fa954b1d-3cbd-4fdd-bbfa-8fe152f3704b)

Iconos PNG

![Device_1_v2_16x16](https://github.com/user-attachments/assets/c32951cb-e498-4afa-aeee-6a63f9515ce3)
![Device_2_16x16](https://github.com/user-attachments/assets/a2e635ad-a13e-4edb-8172-3bfe5631a6b7)
![Device_1_16x16](https://github.com/user-attachments/assets/44826b7e-9449-4ba1-8636-5edda3d3a8c1)
![tag_rojo_lineas_16x16](https://github.com/user-attachments/assets/8545a0b6-6553-4260-8214-184ac311fb71)
![Active_MQ_16x16](https://github.com/user-attachments/assets/a912249a-cbac-4119-a077-02ee84c9ddfc)
![enterprise_16x16](https://github.com/user-attachments/assets/37614f79-e4dc-4e7b-b96d-c35b8825666e)
![site_16x16](https://github.com/user-attachments/assets/53f883a5-522e-4c55-a8a8-d1484c5ee656)
![aliases_16x16](https://github.com/user-attachments/assets/b4a97f45-befd-42f4-85c0-c8c0a6a93fa8)
![IOT_Gateway_16x16](https://github.com/user-attachments/assets/a78e81ed-f143-4e30-9801-15b3cc2e0ddc)
![tag_roja_16x16](https://github.com/user-attachments/assets/e8725ed4-89d2-4f9f-82f7-f38f38718737)
![tag_verde_16x16](https://github.com/user-attachments/assets/8bad1dea-5ee3-4b19-9576-c271869f7e30)
![tag_verde_linea_16x16](https://github.com/user-attachments/assets/4a88774f-326f-4b5a-aba0-227b9be1eb65)
![tag_amarilla_16x16](https://github.com/user-attachments/assets/c846b5a6-0130-44b2-a710-08195fcd49ec)
![tag_amarilla_linea_16x16](https://github.com/user-attachments/assets/973198f0-9e5b-4045-81c4-8d062f5552ce)
![tag_resaltada_16x16](https://github.com/user-attachments/assets/921decd5-7852-49c9-980f-185baa30f2d7)
![tags_doble_16x16](https://github.com/user-attachments/assets/4e73d084-f3b8-456d-bbd8-25c5a21c73f9)
![advance_tags_16x16](https://github.com/user-attachments/assets/f2707564-efb0-42b4-b876-25fb00a20075)
![alarm_events_16x16](https://github.com/user-attachments/assets/730a8728-04cb-4130-90d0-af6647f95e38)
![Data_logger_16x16](https://github.com/user-attachments/assets/7e55ac9d-569b-446e-9d1e-32fa24e0635e)
![TDB_16x16](https://github.com/user-attachments/assets/6458f1fb-bccf-4481-bcee-cfce1170dc96)

Icon SVG

![Device_1_v2_16x16](https://github.com/user-attachments/assets/1eb93e78-d11c-46d9-b086-c654b54925f5)
![Device_2_16x16](https://github.com/user-attachments/assets/4441747c-5926-4823-b01d-3ab889e64de9)
![Device_1_16x16](https://github.com/user-attachments/assets/b237ce79-51b0-4e29-bfe8-459b4c195a0a)
![tag_rojo_lineas_16x16](https://github.com/user-attachments/assets/22222264-a6ef-42c9-b1ff-eab60eb7b744)
![Active_MQ_16x16](https://github.com/user-attachments/assets/1c05782c-ffef-4262-b3db-554653f71370)
![enterprise_16x16](https://github.com/user-attachments/assets/1baadca2-b651-4981-9d0b-5da82fec35f0)
![site_16x16](https://github.com/user-attachments/assets/7e973f60-fb47-49b2-95d4-04bdbd525f2b)
![aliases_16x16](https://github.com/user-attachments/assets/f5f665d0-d2ec-4d1a-8b63-68ddc5a6caaa)
![IOT_Gateway_16x16](https://github.com/user-attachments/assets/32219f85-a174-4c1e-9cb9-742fa76f88cf)
![tag_roja_16x16](https://github.com/user-attachments/assets/dbab17f5-df93-45b1-8cc7-79d257a64a06)
![tag_verde_16x16](https://github.com/user-attachments/assets/9d53a4aa-861f-4573-864f-597103bbccad)
![tag_verde_lineas_16x16](https://github.com/user-attachments/assets/80163181-22d2-472d-a9c8-0258b76b6161)
![tag_amarilla_16x16](https://github.com/user-attachments/assets/7bfa47bc-dc61-4d76-8a40-257ddfc9c5a6)
![tag_amarilla_lineas_16x16](https://github.com/user-attachments/assets/950f8f9f-82a7-4e3f-8ec3-dac54f4a13b0)
![tag_resaltada_16x16](https://github.com/user-attachments/assets/35a3c8b2-6a6d-442a-a18f-484b384e5a98)
![tag_doble_16x16](https://github.com/user-attachments/assets/8191f231-116f-4345-a2f3-6a11cba13188)
![advance_tags_16x16](https://github.com/user-attachments/assets/24503ba2-1315-4cd4-99e7-07c5128390dd)
![alarm_events_16x16](https://github.com/user-attachments/assets/bec87309-e968-40a8-9eb9-8fe2be1dc441)
![Data_logger_16x16](https://github.com/user-attachments/assets/def4b91d-8e3b-49d8-86fa-975707859fd7)
![TDB_16x16](https://github.com/user-attachments/assets/23064537-c161-40c0-9599-f232c3726084)

**Comment by ottlukas** [comment]
This is not an issue please move this to the wiki. Thank you!
